// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmPBuo40HLbjTHV5089Ex3ndDe8gJbAc',
    appId: '1:739730658152:web:b51d1e677c9c8918043cdd',
    messagingSenderId: '739730658152',
    projectId: 'learn-inc-2024',
    authDomain: 'learn-inc-2024.firebaseapp.com',
    storageBucket: 'learn-inc-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbnLQdqZZdu7BVJ4exttQJsXaM32U8PZY',
    appId: '1:739730658152:android:4f97391d8eaf75c9043cdd',
    messagingSenderId: '739730658152',
    projectId: 'learn-inc-2024',
    storageBucket: 'learn-inc-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lNeyeZ9t1NK4S6JfabF335NFR_5odvQ',
    appId: '1:739730658152:ios:29d7be0fd606db4c043cdd',
    messagingSenderId: '739730658152',
    projectId: 'learn-inc-2024',
    storageBucket: 'learn-inc-2024.firebasestorage.app',
    iosBundleId: 'com.example.learnInc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5lNeyeZ9t1NK4S6JfabF335NFR_5odvQ',
    appId: '1:739730658152:ios:29d7be0fd606db4c043cdd',
    messagingSenderId: '739730658152',
    projectId: 'learn-inc-2024',
    storageBucket: 'learn-inc-2024.firebasestorage.app',
    iosBundleId: 'com.example.learnInc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJmPBuo40HLbjTHV5089Ex3ndDe8gJbAc',
    appId: '1:739730658152:web:098ec6d3ee1dd41e043cdd',
    messagingSenderId: '739730658152',
    projectId: 'learn-inc-2024',
    authDomain: 'learn-inc-2024.firebaseapp.com',
    storageBucket: 'learn-inc-2024.firebasestorage.app',
  );

}